# Configurations
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
highlighter: pygments

# Needed for backward compatibility
gems: [jekyll-paginate]

# Permalinks
permalink:        /blog/:year/:month/:day/:title

# Setup
title:            'Yao (Marc) Wang'
tagline:          'A Metro theme for Jekyll'
description:      'Marc Wong personal blog'
url:              'http://192.168.0.1:4000'
baseurl:          ''

# Navigation
navigation:
- text: About
  url: /about/
- text: Resume
  url: /resume/
- text: Blog
  url: /blog/
- text: Tags
  url: /tags/
- text: Archive
  url : /archive/
- text: Search
  url: /search/


# Author Details
author:         'Yao Wang from Peking University'

#Social Media links (Use complete URL except for email)
dribbble:
email:          'yao.staufenberg@gmail.com'
facebook:       'https://www.facebook.com/marcSwong'
flickr:
github:         'https://github.com/marcWong'
gplus:          'https://plus.google.com/113255954925947077823/'
instagram:
pinterest:
linkedin:       
rss:
stackoverflow:  
twitter:        

# Google Analytics
gahandler: 'UA-52149651-1'

#if footersvg is 'true' the social media links will be shown top on the copy right in the footer
footersvg: 'true'

# Disqus
disqushandler: 'testingblogo'

# txtpen
txtpenhandler: 'testingblogo'

# Blog Configurations
paginate: 8 # Posts per page on the blog index
paginate_path: '/blog/page:num'
destination: ./_site

# Custom vars
version:          0.9x beta 2
